# -*- coding: utf-8 -*-
"""ai research paper intelligence system project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARh2rty1FACH7He8QdWqg2uPQCaVHtT2

Setup and Dataset Loading
"""

# Install required libraries
!pip install datasets sentence-transformers pandas numpy -q
from datasets import load_dataset
import pandas as pd
import numpy as np
import os
# Load the ArXiv dataset
dataset = load_dataset("CShorten/ML-ArXiv-Papers")
df = dataset["train"].to_pandas()
print(f"Dataset Loaded. Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

"""Data Cleaning & Preprocessing"""

# Select only title and abstract
df = df[['title', 'abstract']]
# Combine Title and Abstract for full context
df['paper_text'] = df['title'] + " " + df['abstract']
# Clean structural garbage (newlines and extra spaces)
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()
# Use a subset for faster processing
df = df.head(15000)
print("Preprocessing Complete.")
print(f"Sample Processed Text: {df['paper_text'].iloc[0][:200]}...")

"""Loading the Embedding Model"""

from sentence_transformers import SentenceTransformer
# Load the pre-trained model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
print("Model Loaded Successfully.")

"""Generating and Saving Embeddings"""

# Create a data directory to store artifacts
os.makedirs('data', exist_ok=True)
print("Generating Embeddings (this may take time)...")
# We encode the text in batches for efficiency
embeddings = model.encode(
    df["paper_text"].tolist(),
    batch_size=32,
    show_progress_bar=True
)
# Save the embeddings and the cleaned dataframe
np.save("data/arxiv_embeddings.npy", embeddings)
df.to_csv("data/cleaned_arxiv_papers.csv", index=False)

print("All artifacts saved to /data folder.")

"""Environment Setup and Data Loading"""

!pip install faiss-cpu sentence-transformers pandas numpy -q
import faiss
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline
import torch
# Load the saved data and embeddings
df = pd.read_csv("data/cleaned_arxiv_papers.csv")
embeddings = np.load("data/arxiv_embeddings.npy").astype('float32')
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

print(f"System Ready: {len(df)} research papers loaded.")

"""Building the FAISS Index"""

# L2 Normalization is required for Cosine Similarity in FAISS
faiss.normalize_L2(embeddings)
# Create the IndexFlatIP (Inner Product) index
dimension = embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)
index.add(embeddings)

print("FAISS Index successfully built and ready for queries.")

def search_paper(query, k=5):
    #Convert query to vector
    query_embedding = model.encode([query]).astype('float32')
    #Normalize query vector
    faiss.normalize_L2(query_embedding)
    #Search the index
    Q, A = index.search(query_embedding, k)
    #Display results
    for score, idx in zip(Q[0], A[0]):
        print(f"Similarity Score: {score:.4f}")
        print(f"Title: {df.iloc[idx]['title']}")
        print(f"Abstract Preview: {df.iloc[idx]['abstract'][:300]}...")
        print("-" * 50)
    return Q, A
# Test a search
search_paper("deep learning in business management")

"""AI Summarization"""

# Load the summarization model
model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model_t5 = AutoModelForSeq2SeqLM.from_pretrained(model_name)
device = 'cuda' if torch.cuda.is_available() else "cpu"
model_t5.to(device)
def generate_summary(text):
    input_text = "summarize: " + text
    inputs = tokenizer.encode(input_text, return_tensors="pt", max_length=512, truncation=True).to(device)
    summary_ids = model_t5.generate(inputs, max_length=100, min_length=30, length_penalty=2.0, num_beams=4, early_stopping=True)
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)
def searching_n_summarizing(query, k=3):
    Q, A = index.search(model.encode([query]).astype('float32'), k)
    print(f"AI RESEARCH BRIEF FOR: '{query}'")
    for score, idx in zip(Q[0], A[0]):
        print(f"TITLE: {df.iloc[idx]['title']}")
        summary = generate_summary(df.iloc[idx]['abstract'])
        print(f"AI SUMMARY: {summary}")
# Final integrated test
searching_n_summarizing("basics of natural language processing")